"""initial migration

Revision ID: 7d3da738ed93
Revises: 5894b2826851
Create Date: 2025-11-14 17:38:12.384356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3da738ed93'
down_revision = '5894b2826851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
