"""initial migration

Revision ID: e000f7b8f4e5
Revises: 7d3da738ed93
Create Date: 2025-11-14 18:50:07.615127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e000f7b8f4e5'
down_revision = '7d3da738ed93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('full_description')

    # ### end Alembic commands ###
